---
- hosts: all
  become: true
  tasks:
    - name: update repository index for Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution =="Ubuntu"

    - name: install apache2 and php package for Ubuntu servers
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: update repository index for Centos
      dnf:
        update_cache: yes
      when: ansible_distribution == "Centos"

    - name: install apache and php package for Centos servers
      dnf:
        name: 
          - httpd
          - php 
        state: latest
      when: ansible_distribution == "Centos"
