---
- hosts: all
  become: true
  tasks: 
    - name: update repsitory index
      apt: 
        update_cache: yes

    - name: install apapche2 package
      apt: 
        name: apache2
        state: absent

    - name: add php support for apache2
      apt:
        name: libapache2-mod-php
        state: absent 
